/*
 * Copyright Kevin Liu
 * November 18 2013
 * You are free to copy, modify, and distribute this file and its contents but
 * you have to acknowledge the original author in your code.
 */


/**
 * GUIBee class
 * @author Kevin Liu
 */
public class GUIBee extends javax.swing.JFrame {
    private WorkerBee bee = new WorkerBee(001, 100, 10);
    /**
     * Creates new form GuiBeeTest
     */
    public GUIBee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textBeeInfo = new javax.swing.JTextArea();
        buttonSetEnergy = new javax.swing.JButton();
        textEnergy = new javax.swing.JTextField();
        buttonSetWorkEnergy = new javax.swing.JButton();
        buttonWork = new javax.swing.JButton();
        textWorkEnergy = new javax.swing.JTextField();
        buttonDrink = new javax.swing.JButton();
        textWorkUnits = new javax.swing.JTextField();
        textNectar = new javax.swing.JTextField();
        lableUnits = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GUI Bee 1.01");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        textBeeInfo.setColumns(20);
        textBeeInfo.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        textBeeInfo.setRows(5);
        textBeeInfo.setText(bee.getBeeInfo());
        jScrollPane1.setViewportView(textBeeInfo);

        buttonSetEnergy.setText("Set Energy");
        buttonSetEnergy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSetEnergyActionPerformed(evt);
            }
        });

        buttonSetWorkEnergy.setText("Set Work Energy");
        buttonSetWorkEnergy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSetWorkEnergyActionPerformed(evt);
            }
        });

        buttonWork.setText("Work");
        buttonWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWorkActionPerformed(evt);
            }
        });

        buttonDrink.setText("Drink Nectar");
        buttonDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDrinkActionPerformed(evt);
            }
        });

        textNectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNectarActionPerformed(evt);
            }
        });

        lableUnits.setText("Unit(s)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(textNectar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonDrink))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(textWorkUnits)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lableUnits)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonWork))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonSetEnergy))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(textWorkEnergy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonSetWorkEnergy)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSetEnergy))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textWorkEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSetWorkEnergy))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonWork)
                    .addComponent(textWorkUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableUnits))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNectar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDrink))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSetEnergyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSetEnergyActionPerformed
        bee.setEnergyValue(Integer.valueOf(textEnergy.getText()));
        textBeeInfo.setText(bee.getBeeInfo());
    }//GEN-LAST:event_buttonSetEnergyActionPerformed

    private void buttonSetWorkEnergyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSetWorkEnergyActionPerformed
        bee.setWorkEnergy(Integer.valueOf(textWorkEnergy.getText()));
        textBeeInfo.setText(bee.getBeeInfo());
    }//GEN-LAST:event_buttonSetWorkEnergyActionPerformed

    private void buttonWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWorkActionPerformed
        bee.doWork(Integer.valueOf(textWorkUnits.getText()));
        textBeeInfo.setText(bee.getBeeInfo());
    }//GEN-LAST:event_buttonWorkActionPerformed

    private void buttonDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDrinkActionPerformed
        bee.drinkNectar(Integer.valueOf(textNectar.getText()));
        textBeeInfo.setText(bee.getBeeInfo());
    }//GEN-LAST:event_buttonDrinkActionPerformed

    private void textNectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNectarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIBee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIBee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIBee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIBee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIBee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDrink;
    private javax.swing.JButton buttonSetEnergy;
    private javax.swing.JButton buttonSetWorkEnergy;
    private javax.swing.JButton buttonWork;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lableUnits;
    private javax.swing.JTextArea textBeeInfo;
    private javax.swing.JTextField textEnergy;
    private javax.swing.JTextField textNectar;
    private javax.swing.JTextField textWorkEnergy;
    private javax.swing.JTextField textWorkUnits;
    // End of variables declaration//GEN-END:variables
}
